# Generated by Django 2.2.2 on 2019-06-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nephelae_gui', '0002_auto_20190619_1106'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='horizontalcrosssection',
            table='HorizontalCrossSection',
        ),
    ]
