# Generated by Django 2.2.2 on 2019-06-25 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nephelae', '0004_auto_20190620_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudView',
        ),
        migrations.DeleteModel(
            name='HorizontalCrossSection',
        ),
    ]
