# Generated by Django 2.2.2 on 2019-06-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nephelae', '0003_auto_20190619_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.AlterModelTable(
            name='horizontalcrosssection',
            table=None,
        ),
    ]
